# menggunakan schema version "3.7" dari Docker Compose
version: "3.7"

services:
  # pendefinisian service db
  item-db:
    # base image db dari mongo:3
    image: mongo:3

    # pendefinisan volume agar db non volatile ketika direstart
    volumes:
      - app-db:/data/db

  # pendefinisian service aplikasi
  item-app:
    # base image dari item-app docker hub
    image: adityacaturputra/item-app:v1

    # mappingan port yang terekspose dari container (8080) ke port (80)
    ports:
      - 80:8080

    # restart policy
    restart: "always"
    depends_on:
      - item-db

volumes:
  # pendefinisian volumen
  app-db:
